# .github/workflows/test.yml
name: Run Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 18
    - run: npm ci
    - run: python test.py
